### ISSUE TITLE
Error with Version 0.5xxx

### ISSUE THREAD

**Issue by bohrdor** [ShadowDuke/OW_GermanPatch#1]
(Filename: C:/mohawkDepot/Branches/TenCrowns/Assets/GameAssets/Scripts/UI/Components/HelpScreenPanel.cs Line: 1223)

NullReferenceException: Object reference not set to an instance of an object
 with the German patch 2

**Comment by ShadowDuke** [comment]
I havent had time to update it yet. I try the next days.

**Comment by kayloeber** [comment]
Hello, I have the same problem as Bohrdor. Please look over it again.
Greetings Kay

**Comment by ShadowDuke** [comment]
Hi. Why, again? I didnt look over it yet cause i simply dont have time to update it right now. You know how many work this is every time (once a week), 1-2 hours alone for this and i have other mods, too.
I do this for free so be patient. Issnt the game to come out of EA soon anyway, and then have german language?

**Comment by ShadowDuke** [comment]
Updated to latest version along with a lot of changes the devs made in the files, was a lot of work.
