### ISSUE TITLE
Mod nicht auf auf MOD.IO gefunden

### ISSUE THREAD

**Issue by Vanuatufish** [ShadowDuke/OW_GermanPatch#4]
Wenn ich versuche, meinen bestehendes Savegame in Deutsch umzuwandeln, bekomme ich die folgende Meldung:

![modio](https://user-images.githubusercontent.com/87396096/125529351-f1d00698-bf44-4930-a8bc-5967f4e9188e.jpg)

Meine fünfte Zeile des Savegames sieht folgendermaßen aus: Version="Version: 1.0.53207+German Translation Part 1=-1983943"

**Comment by Vanuatufish** [comment]
Die Deutsche Übersetzung ist im Mod-Menü aktiviert.

**Comment by ShadowDuke** [comment]
Nenne in der Savegame Datei anstatt " +German Translation Part ", den
Ordernamen der bei dir in \Documents\My Games\OldWorld\Translations steht.
Es kann sein, dass durch die Umstellung von Early Access auf Release
Version der Name auf german1 geändert wurde?

Also dann Version="Version: 1.0.53207+german1=<bla>

Ich kann das leider gerade nicht so testen. Ich habe 4 verschiedene Versionen und 2 Quellen mit mod.io und github.

Ich habe die Beschreibung diesbezüglich auch mal angepasst, falls das dann der Fall sein sollte.

Edit: Nur für die Änderung im Savegame: Ich glaube, german1 für die mod.io version und wenn du über github beziehst, sieht man ja auf der Hauptseite den tree, müsste es german sein.

Am Di., 13. Juli 2021 um 23:51 Uhr schrieb Vanuatufish <
***@***.***>:

**Comment by Vanuatufish** [comment]
Danke! Das ändern zu Version: 1.0.53207+**german**=-1983943 hat das Problem behoben! Es lag also am Ordnernamen in "Translations".
